language: python
python: 3.6
before_install:
  # as suggested in https://github.com/travis-ci/travis-ci/issues/4990#issuecomment-297863117
  - if [[ $TOXENV = py35 && -f ~/virtualenv/python3.5/bin/activate ]]; then source ~/virtualenv/python3.5/bin/activate; fi
env:  # $ tox -l | sort | xargs -I _ echo '  - TOXENV=_'
  - TOXENV=flake8
  - TOXENV=py27-django18
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py34-django18
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py35-django18
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py36-django111
install:
  - pip install tox
script: tox
