name: Tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PY_COLORS: '1'

jobs:
  python-django:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        django-version:
        - '3.2'
        - '4.1'
        - '4.2'
        - '5.0'
        exclude:
        - { django-version: '3.2', python-version: '3.11' }
        - { django-version: '3.2', python-version: '3.12' }
        - { django-version: '4.1', python-version: '3.7' }
        - { django-version: '4.1', python-version: '3.12' }
        - { django-version: '4.2', python-version: '3.7' }
        - { django-version: '5.0', python-version: '3.7' }
        - { django-version: '5.0', python-version: '3.8' }
        - { django-version: '5.0', python-version: '3.9' }
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install prerequisites
      run: python -m pip install tox-gh-actions
    - name: Run tests (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
      run: tox
      env:
        DJANGO: ${{ matrix.django-version }}
  behave-latest:
    runs-on: ubuntu-latest
    env:
      TOXENV: behave-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install prerequisites
      run: python -m pip install tox
    - name: Run tests (${{ env.TOXENV }})
      run: tox
